version: "3"
services:
  app:
    build: .
    command: node build/main.js
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LAVA_HOST=${LAVA_HOST}
      - LAVA_PORT=${LAVA_PORT}
      - LAVA_PASSWORD=${LAVA_PASSWORD}
      - LAVA_SECURE=${LAVA_SECURE}
